import type { Metadata } from "next";
import { Linden_Hill, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { TamboProvider } from '@/components/providers/TamboProvider';
import { ComponentRegistry } from '@/components/tambo/registry';
import { CommandPalette } from "@/components/command/CommandPallete";

import { KeyboardShortcuts } from "@/components/shortcuts/keyboardShortCuts";
import { Toaster } from '@/components/ui/sonner';
import { ErrorBoundary } from '@/components/error/ErrorBoundary';

const inter = Inter({
  subsets: ["latin"]
})

const linednHill = Linden_Hill({
  variable: "--font-linden-hill",
  subsets: ["latin"],
  weight: "400",

})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} ${linednHill.variable} antialiased`}>
        <ErrorBoundary>
          <TamboProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ComponentRegistry />
              <CommandPalette />
              
              <main className="min-h-screen bg-background ">
                {children}
              </main>
              
              <Toaster
                position="bottom-right"
                toastOptions={{
                  style: {
                    background: 'var(--card)',
                    border: '1px solid var(--border)',
                    color: 'var(--card-foreground)',
                  },
                }}
              />
            </ThemeProvider>
          </TamboProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}

